[package]
name = "coup"
version = "0.1.0"
authors = ["elsid <elsid.mail@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.0"
itertools = "0.10.0"
clap = "3.0.0-beta.2"
serde = { version = "1.0.119", features = ["derive", "rc"] }
serde_json = "1.0.61"
